"use client";

/**
 * next/image custom loader (next.config.ts -> images.loaderFile).
 *
 * - Unsplash URLs are resized on Unsplash's CDN. When the src carries our private
 *   `tm-ar=<height/width>` hint (see cropSrc() in src/lib/img.ts, or the `ratio`
 *   prop of <ParallaxImage>), the loader asks for an aspect-correct crop
 *   (w x round(w * ar)) so a landscape original is never upscaled to fill a
 *   portrait frame.
 * - Brand logos (/brand/<name>.png) map every srcset width to a pre-sized WebP
 *   (/brand/v/<name>-<w>.webp, generated by scripts/brand-variants.mjs), so each
 *   descriptor is honest and the browser never upscales the mark.
 * - Everything else is served as-is.
 */
type LoaderArgs = { src: string; width: number; quality?: number };

/** Must match BRAND_WIDTHS in scripts/brand-variants.mjs (+ the source width). */
const BRAND_WIDTHS = [32, 48, 64, 96, 128, 256, 384, 640, 750, 828, 1080, 1200];
const BRAND_MAX = 1665;
const BRAND_RE = /^\/brand\/([a-z0-9-]+)\.png$/;

export default function imageLoader({ src, width, quality }: LoaderArgs) {
  if (src.startsWith("https://images.unsplash.com/")) {
    const url = new URL(src);
    const ar = parseFloat(url.searchParams.get("tm-ar") ?? "");
    url.searchParams.delete("tm-ar");
    url.searchParams.set("w", String(width));
    if (ar > 0 && Number.isFinite(ar)) {
      url.searchParams.set("h", String(Math.round(width * ar)));
      url.searchParams.set("crop", "faces,entropy");
    }
    url.searchParams.set("q", String(quality ?? 75));
    url.searchParams.set("auto", "format");
    url.searchParams.set("fit", "crop");
    return url.toString();
  }
  const brand = BRAND_RE.exec(src);
  if (brand) {
    const w = BRAND_WIDTHS.find((b) => b >= width) ?? BRAND_MAX;
    return `/brand/v/${brand[1]}-${w}.webp`;
  }
  // Local / other assets: serve as-is (swap for CloudFront resizing later).
  return src;
}
